---
crio_versioned_pkg:
  "1.19":
    - "cri-o=1.19*"
    - cri-o-runc
  "1.18":
    - "cri-o=1.18*"
    - cri-o-runc
  "1.17":
    - "cri-o=1.17*"
    - cri-o-runc

default_crio_packages: "{{ crio_versioned_pkg[crio_version] }}"

crio_packages: "{{ ubuntu_crio_packages | default(default_crio_packages) }}"

crio_runc_path: /usr/sbin/runc

crio_kubernetes_version_matrix:
  "1.18": "1.17"
  "1.17": "1.17"
  "1.16": "1.16"
